contribute an esp32-wroom-32d case design
klaasnicolaas/home-assistant-glow pull request #368
Opened 2024-01-18 19:30 UTC by knaak

I am happy to contribute a ESP32-WROOM-32D outdoor case design for homeassistant-glow which is designed to house and protect an ESP32-WROOM-32D based Home Assistant Glow project from the elements.

2024-01-18 19:54 UTC, klaasnicolaas requested changes

2024-01-18 19:54 UTC, klaasnicolaas commented on docs/docs/reference/cases.mdx
> +
```suggestion
```

2024-01-18 19:54 UTC, klaasnicolaas commented on docs/docs/reference/cases.mdx
> +This case consists of 2 parts, a top and bottom where you can friction fit the pieces over each other and is designed to be used in both an indoor and outdoor environment. The LED status light is des
```suggestion
This case consists of 2 parts, a top and bottom where you can friction fit the pieces over each other and is designed to be used in both an indoor and outdoor environment. The LED status light is designed to slide into the housing and form a relatively tight seal. The USB cable is designed to slide up to provide some protection to water intrusion.
```

2024-01-18 19:54 UTC, klaasnicolaas commented on docs/docs/reference/cases.mdx
> +| ESP32S - Top | Top part of the case for the ESP32D | [Download](/cases/ESP32-WROOM-32D/ESP32-WROOM-32D_top_case.stl)
```suggestion
| ESP32 WROOM - Top | Top part of the case for the ESP32D | [Download](/cases/ESP32-WROOM-32D/ESP32-WROOM-32D_top_case.stl)
```

2024-01-18 19:54 UTC, klaasnicolaas commented on docs/docs/reference/cases.mdx
> +| ESP32S - Bottom | Bottom part of the case for the ESP32D | [Download](/cases/ESP32-WROOM-32D/ESP32-WROOM-32D_bottom_case.stl)
```suggestion
| ESP32 WROOM - Bottom | Bottom part of the case for the ESP32D | [Download](/cases/ESP32-WROOM-32D/ESP32-WROOM-32D_bottom_case.stl)
```

2024-01-18 22:46 UTC, klaasnicolaas commented on docs/docs/reference/cases.mdx
> +If you are familiar with OnShape, you can find the model by searching for \"home-assistant-glow esp32-wroom-case\" where you can make a copy and modify it to your specifications.
Is there some direct link to share?

2024-01-19 02:35 UTC, knaak commented on docs/docs/reference/cases.mdx
> +If you are familiar with OnShape, you can find the model by searching for \"home-assistant-glow esp32-wroom-case\" where you can make a copy and modify it to your specifications.
Yes, in created a share url and added it which should be durable and added it as an option.  I am not exactly sure how mdx files are used, so please check that I created a link successfully.

2024-01-19 04:23 UTC, klaasnicolaas requested changes

2024-01-19 04:23 UTC, klaasnicolaas commented on docs/docs/reference/cases.mdx
> +If you are familiar with OnShape, you can find the model by searching for \"home-assistant-glow esp32-wroom-case\" where you can make a copy and modify it to your specifications, or by using this lin
```suggestion
If you're familiar with OnShape, you can access the model using [this link](https://cad.onshape.com/documents/28a914bca0ab451bdef13eb6/w/61ae11d2b0e90a508761a159/e/b81866b90bb3011f3cadb1f2). Simply make a copy and customize it according to your specifications. Please note that having an account might be necessary to make adjustments.
```

2024-01-19 14:19 UTC, klaasnicolaas approved these changes

2024-01-19 16:57 UTC, merged